[package]
name = "caps"
version = "1.5.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.8.0" }
starknet = "2.13"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "=2.13"

[profile.sepolia]