[package]
name = "caps_core"
version = "0.1.0"
edition = "2024_07"


[lib]
# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.8.2" }

[dev-dependencies]
cairo_test = "2.12.2"
